### ISSUE TITLE
Um this doesn't seem to work for me

### ISSUE THREAD

**Issue by gandhiShepard** [ivanoats/gatsby-blog-json-data#1]
I followed your install steps and it didn't work. I just get a blank screen.

After a ton of Webpack output I get this error
```
ERROR in ./~/gatsby/dist/utils/web-entry.js
Module not found: Error: Cannot resolve module '.gatsby-context'
```
This isn't a high pressure issue. Just wanted you to know if others are having the same issue. I was hoping to explore how the graphql worked.
Stay awesome!
Best regards,

Ben

**Comment by ivanoats** [comment]
This is just a test repo - it wasn’t meant as an example for anyone else but me, sorry. I think Gatsby has updated since I made this.

**Comment by gandhiShepard** [comment]
No problem! Yeah, Gatsby is being updated rapidly. Cheers!
